name: Deploy

on:
  push:
    branches:
      - releases/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Yandex Cloud Container Registry
        run: echo "${{ secrets.YC_REGISTRY_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Verify Docker image
        run: docker manifest inspect cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:${{ github.event.inputs.version }}

      - name: Deploy to Production
        run: |
          ssh -i ${{ secrets.VM_SSH_KEY }} ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} "docker pull cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:${{ github.event.inputs.version }} && docker run -d -p 3000:3000 cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:${{ github.event.inputs.version }}"

      - name: Add release comment to Issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { ref, head_commit } = context.payload;
            const { login } = await github.users.getByUsername({ username: context.actor });
            const body = `Release ${ref} deployed to production by ${login} at ${new Date().toISOString()}`;
            await github.issues.createComment({ owner, repo, issue_number: context.issue.number, body });
