name: Deploy

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version of the release to deploy'
        required: true

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Yandex Container Registry
        run: echo ${{ secrets.YC_REGISTRY_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

      - name: Check Docker image existence in Container Registry
        run: |
          IMAGE="cr.yandex/crp7jeuq66rvk2nacuqp/app:${{ github.event.inputs.release_version }}_latest"
          if docker pull $IMAGE; then
            echo "Docker image $IMAGE found."
          else
            echo "Error: Docker image $IMAGE not found."
            exit 1
          fi


      - name: Stop and remove existing container if running
        run: |
          CONTAINER_ID=$(docker ps -aqf "name=shri-infra")
          if [ -n "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          else
            echo "No existing container with name shri-infra found."
          fi  

      - name: Deploy to production server
        env:
          SERVER_IP: ${{ secrets.VM_IP }}
          SERVER_USER: ${{ secrets.VM_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/shrikeys
          chmod 600 ~/.ssh/shrikeys
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/shrikeys ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            # Check for existing container
            CONTAINER_ID=$(docker ps -aqf "name=shri-infra")
            if [ -n "$CONTAINER_ID" ]; then
              docker stop $CONTAINER_ID
              docker rm $CONTAINER_ID
            else
              echo "No existing container with name shri-infra found."
            fi  
            
            # Pull and run the new container
            docker pull cr.yandex/crp7jeuq66rvk2nacuqp/app:${{ github.event.inputs.release_version }}_latest
            docker run -d -p 3000:3000 cr.yandex/crp7jeuq66rvk2nacuqp/app:${{ github.event.inputs.release_version }}_latest
            
            # Wait for the container to start
            sleep 10
            
            # Check container logs
            docker logs shri-infra
            
            # Check running containers
            docker ps
          EOF

      - name: Comment on GitHub Issue about deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Релиз ${{ github.event.inputs.release_version }} успешно выкачен в прод на $(date) пользователем $GITHUB_ACTOR." > comment.txt
          gh issue comment $(gh issue list --search "Релиз ${{ github.event.inputs.release_version }}" --json number --jq '.[0].number') --body-file comment.txt