name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Yandex Cloud Container Registry
        run: echo "${{ secrets.YC_REGISTRY_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Build and push Docker image
        run: |
          docker build -t cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:11 .
          docker push cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:11

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Yandex Cloud Container Registry
        run: echo "${{ secrets.YC_REGISTRY_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Pull Docker image
        run: docker pull cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:11

      - name: Deploy to VM
        run: |
          ssh -i ${{ secrets.VM_SSH_KEY }} ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} "docker pull cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:11 && docker run -d -p 80:80 cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:11"
