name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
        default: '1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Yandex Cloud Container Registry
        env:
          YC_REGISTRY_TOKEN: ${{ secrets.YC_REGISTRY_TOKEN }}
        run: echo "${{ secrets.YC_REGISTRY_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Check if Docker image exists
        id: image_check
        run: |
          VERSION=${{ github.event.inputs.version }}
          if ! docker manifest inspect cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:${VERSION}_latest; then
            echo "Docker image with version ${VERSION}_latest does not exist."
            exit 1
          fi

      - name: Deploy to VM
        env:
          VM_IP: ${{ secrets.VM_IP }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_SSH_KEY: ${{ secrets.VM_SSH_KEY }}
        run: |
          VERSION=${{ github.event.inputs.version }}
          ssh -i $VM_SSH_KEY -o StrictHostKeyChecking=no $VM_USER@$VM_IP << EOF
            docker pull cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:${VERSION}_latest
            docker run -d -p 80:80 cr.yandex/crp7jeuq66rvk2nacuqp/shri-infra:${VERSION}_latest
          EOF

      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1 # Replace with your issue number
          body: |
            Release ${{ github.event.inputs.version }} has been deployed to production.
            Date: ${{ steps.current_date.outputs.date }}
            Deployed by: ${{ github.actor }}
